In [31]:
import numpy as np

In [32]:
minha_lista = [1, 2, 3]
minha_lista

[1, 2, 3]

In [33]:
np.array(minha_lista)

array([1, 2, 3])

In [34]:
minha_matriz = [[1, 2, 3], [4, 5 , 6], [7, 8, 9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [35]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [38]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [40]:
arr = np.zeros((5, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [44]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [45]:
np.random.rand(5)

array([0.54294877, 0.75865214, 0.99085733, 0.35670269, 0.35111874])

In [46]:
np.random.rand(5, 4)

array([[0.97781359, 0.00116544, 0.2445368 , 0.18339067],
       [0.31639358, 0.97439055, 0.03760918, 0.80984921],
       [0.04434258, 0.25431629, 0.80043978, 0.75241757],
       [0.58130175, 0.87920158, 0.86897626, 0.89899325],
       [0.42648573, 0.74199569, 0.40646886, 0.42307741]])

In [47]:
np.random.randn(4)

array([-0.03464397, -0.37697455,  0.924983  ,  0.04878998])

In [48]:
np.random.randint(0, 100, 10)

array([73, 55, 81, 46, 47, 56,  6, 97, 48, 37])

In [49]:
np.round(np.random.rand(5) * 100, 0)

array([16., 61., 12., 14., 49.])

In [50]:
arr = np.random.rand(25)
arr

array([0.74392331, 0.83264797, 0.31264811, 0.9645699 , 0.07653194,
       0.60414124, 0.23361778, 0.0013676 , 0.05741497, 0.26624752,
       0.13197092, 0.05680455, 0.30481077, 0.47136707, 0.67569714,
       0.9828731 , 0.06464714, 0.6992976 , 0.10599278, 0.81274674,
       0.96333932, 0.26685531, 0.404187  , 0.70334607, 0.08231274])

In [51]:
arr.reshape((5, 5))

array([[0.74392331, 0.83264797, 0.31264811, 0.9645699 , 0.07653194],
       [0.60414124, 0.23361778, 0.0013676 , 0.05741497, 0.26624752],
       [0.13197092, 0.05680455, 0.30481077, 0.47136707, 0.67569714],
       [0.9828731 , 0.06464714, 0.6992976 , 0.10599278, 0.81274674],
       [0.96333932, 0.26685531, 0.404187  , 0.70334607, 0.08231274]])

In [53]:
arr = arr.reshape((5, 5))
arr

array([[0.74392331, 0.83264797, 0.31264811, 0.9645699 , 0.07653194],
       [0.60414124, 0.23361778, 0.0013676 , 0.05741497, 0.26624752],
       [0.13197092, 0.05680455, 0.30481077, 0.47136707, 0.67569714],
       [0.9828731 , 0.06464714, 0.6992976 , 0.10599278, 0.81274674],
       [0.96333932, 0.26685531, 0.404187  , 0.70334607, 0.08231274]])

In [57]:
arr.shape

(5, 5)

In [58]:
arr.max()

0.9828730972755051

In [59]:
arr.min()

0.0013675972383051516

In [60]:
arr.argmax()

15

In [61]:
arr.argmin()

7